import '@/styles/globals.css'
import { MoralisProvider } from 'react-moralis'
import Head from 'next/head'
import Headers from '@/components/header'

export default function App({ Component, pageProps }) {

  return (
    <div>
      <Head>
        <title>Student details</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MoralisProvider initializeOnMount={false}>
        <Headers/>
        <Component {...pageProps} />
      </MoralisProvider>
    </div>
    
  )
}
