import Headers from '@/components/Header'
import '@/styles/globals.css'
import { MoralisProvider } from 'react-moralis'
import { NotificationProvider } from 'web3uikit'
import Head from 'next/head'

export default function App({ Component, pageProps }) {

  return (
    <div>        
      <MoralisProvider initializeOnMount={false}>
        <NotificationProvider>
          <Head>
              <title>Student details</title>
              <meta name="description" content="Generated by create next app" />
              <meta name="viewport" content="width=device-width, initial-scale=1" />
              <link rel="icon" href="/favicon.ico" />
          </Head>
          <Headers/>
          <Component {...pageProps} />
        </NotificationProvider>        
      </MoralisProvider>

    </div>
      
  )
}
